# Generated by Django 5.2.1 on 2025-05-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatosColegio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
