# Generated by Django 5.2.1 on 2025-05-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatosColegio', '0002_horario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='12345678', max_length=15),
        ),
    ]
