# Generated by Django 5.2.1 on 2025-05-25 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatosColegio', '0003_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso_paralelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseDatosColegio.cursoparalelo'),
        ),
    ]
