# Generated by Django 5.2.1 on 2025-05-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatosColegio', '0004_alumno_curso_paralelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='curso',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participacion',
            name='materia',
            field=models.IntegerField(null=True),
        ),
    ]
