# Generated by Django 5.2.1 on 2025-05-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatosColegio', '0006_notificacion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='comentario',
        ),
    ]
