# Generated by Django 5.2.1 on 2025-05-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatosColegio', '0007_remove_asistencia_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='horario_materia',
        ),
        migrations.AddField(
            model_name='tareaasignada',
            name='horario_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseDatosColegio.horariomateria'),
        ),
    ]
