# Generated by Django 5.2.1 on 2025-05-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatosColegio', '0008_remove_actividad_horario_materia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='curso_paralelo',
        ),
        migrations.CreateModel(
            name='AlumnoCursoParalelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatosColegio.alumno')),
                ('curso_paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatosColegio.cursoparalelo')),
            ],
            options={
                'unique_together': {('curso_paralelo', 'alumno')},
            },
        ),
    ]
