# Generated by Django 5.2.1 on 2025-05-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatosColegio', '0009_remove_alumno_curso_paralelo_alumnocursoparalelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareaasignada',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='tareaasignada',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='tareaasignada',
            name='descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
