# Generated by Django 5.2.1 on 2025-05-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatosColegio', '0010_remove_tareaasignada_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnocursoparalelo',
            name='gestion_id',
            field=models.IntegerField(null=True),
        ),
    ]
